"use client";

import { useState, useMemo } from "react";
import DashboardLayout from "@/app/components/Admin/common/dashboard_layout";
import SearchBar from "@/app/components/Admin/common/Search-bar";
import DateRangeBar from "@/app/components/Admin/common/DateRangeBar";
import ExportReportPanel from "@/app/components/Admin/reports/ExportReportPanel";
import ReportStatCardGrid from "@/app/components/Admin/reports/ReportStatCardGrid";
import ReportChart from "@/app/components/Admin/reports/ReportChart";
import ReportActionsBar from "@/app/components/Admin/reports/ReportActionsBar";
import ReportTable from "@/app/components/Admin/reports/ReportTable";

import {
  SALES_DATA,   SALE_COLUMNS,
  EXPENSES_DATA, EXPENSE_COLUMNS,
  PRODUCTS_DATA, PRODUCT_COLUMNS,
  type SaleRow, type ExpenseRow, type ProductRow,
} from "@/app/reports/reportsMockData";

type TableTab = "sales" | "expenses" | "products";

const EXPORT_CONFIG: Record<
  TableTab,
  { data: any[]; columns: any[]; filename: string; title: string; subtitle: string }
> = {
  sales: {
    data:     SALES_DATA,
    columns:  SALE_COLUMNS,
    filename: "sales-report",
    title:    "Sales Report",
    subtitle: "January 2026 – All sales transactions",
  },
  expenses: {
    data:     EXPENSES_DATA,
    columns:  EXPENSE_COLUMNS,
    filename: "expenses-report",
    title:    "Expenses Report",
    subtitle: "January 2026 – All expense records",
  },
  products: {
    data:     PRODUCTS_DATA,
    columns:  PRODUCT_COLUMNS,
    filename: "products-report",
    title:    "Products Report",
    subtitle: "January 2026 – Top selling products",
  },
};


export default function ReportsPage() {
  const [search,    setSearch]    = useState("");
  const [chartTab,  setChartTab]  = useState("sales-trends");
  const [tableTab,  setTableTab]  = useState<TableTab>("sales");
  const [startDate, setStartDate] = useState<Date | undefined>(new Date("2026-01-20"));
  const [endDate,   setEndDate]   = useState<Date | undefined>(new Date("2026-01-28"));

  const [selectedSale,    setSelectedSale]    = useState<SaleRow    | null>(null);
  const [selectedExpense, setSelectedExpense] = useState<ExpenseRow | null>(null);
  const [selectedProduct, setSelectedProduct] = useState<ProductRow | null>(null);

  const hasSelection =
    (tableTab === "sales"    && selectedSale    !== null) ||
    (tableTab === "expenses" && selectedExpense !== null) ||
    (tableTab === "products" && selectedProduct !== null);

  const handleTabChange = (tab: string) => {
    setTableTab(tab as TableTab);
    setSelectedSale(null);
    setSelectedExpense(null);
    setSelectedProduct(null);
    setSearch("");
  };

  const handleViewDetails = () => {
    if (tableTab === "sales"    && selectedSale)    alert(`Invoice: ${selectedSale.invoiceId}\nCustomer: ${selectedSale.customer}\nAmount: $${selectedSale.amount}`);
    if (tableTab === "expenses" && selectedExpense) alert(`Category: ${selectedExpense.category}\nDesc: ${selectedExpense.description}\nAmount: $${selectedExpense.amount}`);
    if (tableTab === "products" && selectedProduct) alert(`SKU: ${selectedProduct.sku}\nProduct: ${selectedProduct.name}\nRevenue: $${selectedProduct.revenue}`);
  };

  const exportConfig = EXPORT_CONFIG[tableTab];

  return (
    <DashboardLayout>
      <div className="w-full space-y-6">

        <ReportStatCardGrid />

        <DateRangeBar
          startDate={startDate}
          endDate={endDate}
          onChange={(s, e) => { setStartDate(s); setEndDate(e); }}
        />

        <div className="flex flex-col lg:flex-row gap-6">
          <ReportChart
            activeTab={chartTab}
            onTabChange={setChartTab}
          />

          <div className="w-full lg:w-[280px] shrink-0">
            <ExportReportPanel
              data={exportConfig.data}
              filename={exportConfig.filename}
              columns={exportConfig.columns}
              pdfOptions={{
                title:    exportConfig.title,
                subtitle: exportConfig.subtitle,
                footer:   "Generated by Coca POS – Reports System",
              }}
            />
          </div>
        </div>

        <SearchBar
          value={search}
          onChange={setSearch}
          placeholder={`Search ${tableTab}...`}
          debounceMs={300}
        />

        <ReportActionsBar
          activeTab={tableTab}
          onTabChange={handleTabChange}
          hasSelection={hasSelection}
          onViewDetails={handleViewDetails}
        />

        <ReportTable
          activeTab={tableTab}
          search={search}
          selectedSale={selectedSale}       onSelectSale={setSelectedSale}
          selectedExpense={selectedExpense} onSelectExpense={setSelectedExpense}
          selectedProduct={selectedProduct} onSelectProduct={setSelectedProduct}
        />

      </div>
    </DashboardLayout>
  );
}