import { RecurringExpenses } from "@/components/Admin/recexpenses/RecExpensesTable";

export const mockRecurringExpenses: RecurringExpenses[] = [
  
  {
    id: "001",
    date: "2026-02-01",
    category: "Rent",
    description: "Monthly rent - Colombo branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "002",
    date: "2026-02-01",
    category: "Rent",
    description: "Monthly rent - Kandy branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "003",
    date: "2026-02-01",
    category: "Rent",
    description: "Monthly rent - Galle branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "004",
    date: "2026-02-05",
    category: "Utilities",
    description: "Electricity bill - Colombo",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "005",
    date: "2026-02-05",
    category: "Utilities",
    description: "Electricity bill - Kandy",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "006",
    date: "2026-02-05",
    category: "Utilities",
    description: "Electricity bill - Galle",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "007",
    date: "2026-02-10",
    category: "Utilities",
    description: "Water bill - Colombo",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "008",
    date: "2026-02-10",
    category: "Utilities",
    description: "Water bill - Kandy",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "009",
    date: "2026-02-10",
    category: "Utilities",
    description: "Water bill - Galle",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "010",
    date: "2026-02-12",
    category: "Salary",
    description: "Staff salaries - Colombo",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "011",
    date: "2026-02-12",
    category: "Salary",
    description: "Staff salaries - Kandy",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "012",
    date: "2026-02-12",
    category: "Salary",
    description: "Staff salaries - Galle",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "013",
    date: "2026-02-15",
    category: "Internet",
    description: "Internet bill - Colombo",
    amount: 20,
    payment: "Card",
    addedby: "Manager",
    branch: "Colombo",
  },
  {
    id: "014",
    date: "2026-02-15",
    category: "Internet",
    description: "Internet bill - Kandy",
    amount: 20,
    payment: "Card",
    addedby: "Manager",
    branch: "Kandy",
  },
  {
    id: "015",
    date: "2026-02-15",
    category: "Internet",
    description: "Internet bill - Galle",
    amount: 20,
    payment: "Card",
    addedby: "Manager",
    branch: "Galle",
  },
  {
    id: "016",
    date: "2026-02-20",
    category: "Telephone",
    description: "Telephone bill - Colombo",
    amount: 10,
    payment: "Card",
    addedby: "Manager",
    branch: "Colombo",
  },
  {
    id: "017",
    date: "2026-02-20",
    category: "Telephone",
    description: "Telephone bill - Kandy",
    amount: 10,
    payment: "Card",
    addedby: "Manager",
    branch: "Kandy",
  },
  {
    id: "018",
    date: "2026-02-20",
    category: "Telephone",
    description: "Telephone bill - Galle",
    amount: 10,
    payment: "Card",
    addedby: "Manager",
    branch: "Galle",
  },
  {
    id: "019",
    date: "2026-02-25",
    category: "Insurance",
    description: "Monthly insurance premium",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },

  // January 2026 - Previous month
  {
    id: "020",
    date: "2026-01-01",
    category: "Rent",
    description: "Monthly rent - Colombo branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "021",
    date: "2026-01-01",
    category: "Rent",
    description: "Monthly rent - Kandy branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "022",
    date: "2026-01-01",
    category: "Rent",
    description: "Monthly rent - Galle branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "023",
    date: "2026-01-05",
    category: "Utilities",
    description: "Electricity bill - Colombo",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "024",
    date: "2026-01-05",
    category: "Utilities",
    description: "Electricity bill - Kandy",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "025",
    date: "2026-01-05",
    category: "Utilities",
    description: "Electricity bill - Galle",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "026",
    date: "2026-01-10",
    category: "Utilities",
    description: "Water bill - Colombo",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "027",
    date: "2026-01-10",
    category: "Utilities",
    description: "Water bill - Kandy",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "028",
    date: "2026-01-10",
    category: "Utilities",
    description: "Water bill - Galle",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "029",
    date: "2026-01-12",
    category: "Salary",
    description: "Staff salaries - Colombo",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "030",
    date: "2026-01-12",
    category: "Salary",
    description: "Staff salaries - Kandy",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "031",
    date: "2026-01-12",
    category: "Salary",
    description: "Staff salaries - Galle",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "032",
    date: "2026-01-15",
    category: "Internet",
    description: "Internet bill - Colombo",
    amount: 20,
    payment: "Card",
    addedby: "Manager",
    branch: "Colombo",
  },
  {
    id: "033",
    date: "2026-01-15",
    category: "Internet",
    description: "Internet bill - Kandy",
    amount: 20,
    payment: "Card",
    addedby: "Manager",
    branch: "Kandy",
  },
  {
    id: "034",
    date: "2026-01-15",
    category: "Internet",
    description: "Internet bill - Galle",
    amount: 20,
    payment: "Card",
    addedby: "Manager",
    branch: "Galle",
  },
  {
    id: "035",
    date: "2026-01-20",
    category: "Telephone",
    description: "Telephone bill - Colombo",
    amount: 10,
    payment: "Card",
    addedby: "Manager",
    branch: "Colombo",
  },
  {
    id: "036",
    date: "2026-01-20",
    category: "Telephone",
    description: "Telephone bill - Kandy",
    amount: 10,
    payment: "Card",
    addedby: "Manager",
    branch: "Kandy",
  },
  {
    id: "037",
    date: "2026-01-20",
    category: "Telephone",
    description: "Telephone bill - Galle",
    amount: 10,
    payment: "Card",
    addedby: "Manager",
    branch: "Galle",
  },
  {
    id: "038",
    date: "2026-01-25",
    category: "Insurance",
    description: "Monthly insurance premium",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },

  // December 2025
  {
    id: "039",
    date: "2025-12-01",
    category: "Rent",
    description: "Monthly rent - Colombo branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "040",
    date: "2025-12-01",
    category: "Rent",
    description: "Monthly rent - Kandy branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "041",
    date: "2025-12-01",
    category: "Rent",
    description: "Monthly rent - Galle branch",
    amount: 20,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "042",
    date: "2025-12-05",
    category: "Utilities",
    description: "Electricity bill - Colombo",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "043",
    date: "2025-12-05",
    category: "Utilities",
    description: "Electricity bill - Kandy",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "044",
    date: "2025-12-05",
    category: "Utilities",
    description: "Electricity bill - Galle",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
  {
    id: "045",
    date: "2025-12-12",
    category: "Salary",
    description: "Staff salaries - Colombo",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Colombo",
  },
  {
    id: "046",
    date: "2025-12-12",
    category: "Salary",
    description: "Staff salaries - Kandy",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Kandy",
  },
  {
    id: "047",
    date: "2025-12-12",
    category: "Salary",
    description: "Staff salaries - Galle",
    amount: 10,
    payment: "Bank Transfer",
    addedby: "Admin",
    branch: "Galle",
  },
];