import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import { CurrencyProvider } from "@/app/context/CurrencyContext";
import { ImageProvider } from "@/app/context/ImageContext";
import { PosSettingsProvider } from "@/app/context/PosSettingsContext";
import { NotificationsProvider } from "./components/Admin/notifications/NotificationsContext";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${poppins.className} ${geistMono.variable} antialiased`}
      >
        <CurrencyProvider>
          <ImageProvider>
            <PosSettingsProvider>
              <NotificationsProvider>
                {children}
              </NotificationsProvider>
            </PosSettingsProvider>
          </ImageProvider>
        </CurrencyProvider>
      </body>
    </html>
  );
}
