import { Expenses } from "@/components/Admin/expensesmanagement/ExpensesTable";

export const mockExpenses: Expenses[] = [
  {
    id: "001",
    expenseId: "001",
    date: "2026-02-22",
    category: "Equipment",
    categoryId: "",
    description: "New coffee machine",
    amount: 20,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Admin",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "002",
    expenseId: "002",
    date: "2026-02-21",
    category: "Maintenance",
    categoryId: "",
    description: "AC repair",
    amount: 10,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Manager",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "003",
    expenseId: "003",
    date: "2026-02-20",
    category: "Marketing",
    categoryId: "",
    description: "Social media ads",
    amount: 20,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Admin",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "004",
    expenseId: "004",
    date: "2026-02-19",
    category: "Equipment",
    categoryId: "",
    description: "Blender replacement",
    amount: 10,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Manager",
    branch: "Galle",
    branchId: "",
  },
  {
    id: "005",
    expenseId: "005",
    date: "2026-02-18",
    category: "Maintenance",
    categoryId: "",
    description: "Plumbing repair",
    amount: 20,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Admin",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "006",
    expenseId: "006",
    date: "2026-02-17",
    category: "Marketing",
    categoryId: "",
    description: "Print advertisements",
    amount: 10,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Manager",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "007",
    expenseId: "007",
    date: "2026-02-16",
    category: "Equipment",
    categoryId: "",
    description: "New refrigerator",
    amount: 20,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Admin",
    branch: "Galle",
    branchId: "",
  },
  {
    id: "008",
    expenseId: "008",
    date: "2026-02-15",
    category: "Maintenance",
    categoryId: "",
    description: "Painting",
    amount: 10,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Manager",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "009",
    expenseId: "009",
    date: "2026-02-14",
    category: "Marketing",
    categoryId: "",
    description: "Influencer collaboration",
    amount: 20,
    payment: "Bank Transfer",
    paymentType: "CASH",
    addedby: "Admin",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "010",
    expenseId: "010",
    date: "2026-02-13",
    category: "Equipment",
    categoryId: "",
    description: "Tables and chairs",
    amount: 10,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Manager",
    branch: "Galle",
    branchId: "",
  },
  {
    id: "011",
    expenseId: "011",
    date: "2026-02-12",
    category: "Maintenance",
    categoryId: "",
    description: "Electrical wiring",
    amount: 20,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Admin",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "012",
    expenseId: "012",
    date: "2026-02-11",
    category: "Marketing",
    categoryId: "",
    description: "Flyer printing",
    amount: 10,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Manager",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "013",
    expenseId: "013",
    date: "2026-01-25",
    category: "Equipment",
    categoryId: "",
    description: "Microwave oven",
    amount: 20,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Admin",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "014",
    expenseId: "014",
    date: "2026-01-20",
    category: "Maintenance",
    categoryId: "",
    description: "Window repair",
    amount: 10,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Manager",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "015",
    expenseId: "015",
    date: "2026-01-18",
    category: "Marketing",
    categoryId: "",
    description: "Billboard rental",
    amount: 20,
    payment: "Bank Transfer",
    paymentType: "CASH",
    addedby: "Admin",
    branch: "Galle",
    branchId: "",
  },
  {
    id: "016",
    expenseId: "016",
    date: "2026-01-15",
    category: "Equipment",
    categoryId: "",
    description: "Cash register",
    amount: 10,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Manager",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "017",
    expenseId: "017",
    date: "2026-01-12",
    category: "Maintenance",
    categoryId: "",
    description: "Door handle replacement",
    amount: 20,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Admin",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "018",
    expenseId: "018",
    date: "2026-01-10",
    category: "Marketing",
    categoryId: "",
    description: "Radio advertisement",
    amount: 10,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Manager",
    branch: "Galle",
    branchId: "",
  },
  {
    id: "019",
    expenseId: "019",
    date: "2026-01-08",
    category: "Equipment",
    categoryId: "",
    description: "Food warmer",
    amount: 20,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Admin",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "020",
    expenseId: "020",
    date: "2026-01-05",
    category: "Maintenance",
    categoryId: "",
    description: "Lighting installation",
    amount: 10,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Manager",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "021",
    expenseId: "021",
    date: "2025-12-15",
    category: "Equipment",
    categoryId: "",
    description: "Ice cream machine",
    amount: 20,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Admin",
    branch: "Galle",
    branchId: "",
  },
  {
    id: "022",
    expenseId: "022",
    date: "2025-12-10",
    category: "Marketing",
    categoryId: "",
    description: "New Year promotion",
    amount: 10,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Manager",
    branch: "Colombo",
    branchId: "",
  },
  {
    id: "023",
    expenseId: "023",
    date: "2025-11-20",
    category: "Maintenance",
    categoryId: "",
    description: "Floor tiling",
    amount: 20,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Admin",
    branch: "Kandy",
    branchId: "",
  },
  {
    id: "024",
    expenseId: "024",
    date: "2025-11-05",
    category: "Equipment",
    categoryId: "",
    description: "Industrial mixer",
    amount: 10,
    payment: "Card",
    paymentType: "CARD",
    addedby: "Manager",
    branch: "Galle",
    branchId: "",
  },
  {
    id: "025",
    expenseId: "025",
    date: "2025-10-28",
    category: "Marketing",
    categoryId: "",
    description: "Grand opening banners",
    amount: 20,
    payment: "Cash",
    paymentType: "CASH",
    addedby: "Admin",
    branch: "Colombo",
    branchId: "",
  },
];