import { Profit } from "@/components/Admin/profitcalculation/ProfitTable";

export const mockProfits: Profit[] = [
  {
    id: "P001",
    date: "2026-02-22",
    category: "Sales",
    description: "Daily sales - Colombo branch",
    profit: 20,
    payment: "Cash",
    branch: "Colombo",
  },
  {
    id: "P002",
    date: "2026-02-22",
    category: "Sales",
    description: "Daily sales - Kandy branch",
    profit: 10,
    payment: "Cash",
    branch: "Kandy",
  },
  {
    id: "P003",
    date: "2026-02-22",
    category: "Sales",
    description: "Daily sales - Galle branch",
    profit: 20,
    payment: "Cash",
    branch: "Galle",
  },
  {
    id: "P004",
    date: "2026-02-21",
    category: "Sales",
    description: "Daily sales - Colombo branch",
    profit: 10,
    payment: "Card",
    branch: "Colombo",
  },
  {
    id: "P005",
    date: "2026-02-21",
    category: "Sales",
    description: "Daily sales - Kandy branch",
    profit: 20,
    payment: "Card",
    branch: "Kandy",
  },
  {
    id: "P006",
    date: "2026-02-21",
    category: "Sales",
    description: "Daily sales - Galle branch",
    profit: 10,
    payment: "Cash",
    branch: "Galle",
  },
  {
    id: "P007",
    date: "2026-02-20",
    category: "Sales",
    description: "Weekend sales - Colombo",
    profit: 20,
    payment: "Mixed",
    branch: "Colombo",
  },
  {
    id: "P008",
    date: "2026-02-20",
    category: "Sales",
    description: "Weekend sales - Kandy",
    profit: 10,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P009",
    date: "2026-02-20",
    category: "Sales",
    description: "Weekend sales - Galle",
    profit: 20,
    payment: "Mixed",
    branch: "Galle",
  },
  {
    id: "P010",
    date: "2026-02-19",
    category: "Sales",
    description: "Daily sales - Colombo",
    profit: 10,
    payment: "Card",
    branch: "Colombo",
  },
  {
    id: "P011",
    date: "2026-02-19",
    category: "Sales",
    description: "Daily sales - Kandy",
    profit: 20,
    payment: "Cash",
    branch: "Kandy",
  },
  {
    id: "P012",
    date: "2026-02-19",
    category: "Sales",
    description: "Daily sales - Galle",
    profit: 10,
    payment: "Card",
    branch: "Galle",
  },
  {
    id: "P013",
    date: "2026-02-18",
    category: "Sales",
    description: "Daily sales - Colombo",
    profit: 20,
    payment: "Cash",
    branch: "Colombo",
  },
  {
    id: "P014",
    date: "2026-02-18",
    category: "Sales",
    description: "Daily sales - Kandy",
    profit: 10,
    payment: "Card",
    branch: "Kandy",
  },
  {
    id: "P015",
    date: "2026-02-18",
    category: "Sales",
    description: "Daily sales - Galle",
    profit: 20,
    payment: "Cash",
    branch: "Galle",
  },
  {
    id: "P016",
    date: "2026-02-17",
    category: "Catering",
    description: "Corporate event - Colombo",
    profit: 20,
    payment: "Bank Transfer",
    branch: "Colombo",
  },
  {
    id: "P017",
    date: "2026-02-16",
    category: "Catering",
    description: "Private party - Kandy",
    profit: 10,
    payment: "Card",
    branch: "Kandy",
  },
  {
    id: "P018",
    date: "2026-02-15",
    category: "Catering",
    description: "Wedding event - Galle",
    profit: 20,
    payment: "Bank Transfer",
    branch: "Galle",
  },
  {
    id: "P019",
    date: "2026-02-14",
    category: "Sales",
    description: "Valentine's Day special",
    profit: 10,
    payment: "Mixed",
    branch: "Colombo",
  },
  {
    id: "P020",
    date: "2026-02-14",
    category: "Sales",
    description: "Valentine's Day special",
    profit: 20,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P021",
    date: "2026-01-31",
    category: "Sales",
    description: "Monthly total - Colombo",
    profit: 20,
    payment: "Mixed",
    branch: "Colombo",
  },
  {
    id: "P022",
    date: "2026-01-31",
    category: "Sales",
    description: "Monthly total - Kandy",
    profit: 10,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P023",
    date: "2026-01-31",
    category: "Sales",
    description: "Monthly total - Galle",
    profit: 20,
    payment: "Mixed",
    branch: "Galle",
  },
  {
    id: "P024",
    date: "2026-01-25",
    category: "Catering",
    description: "Birthday party - Colombo",
    profit: 10,
    payment: "Card",
    branch: "Colombo",
  },
  {
    id: "P025",
    date: "2026-01-20",
    category: "Catering",
    description: "Anniversary event - Kandy",
    profit: 20,
    payment: "Bank Transfer",
    branch: "Kandy",
  },
  {
    id: "P026",
    date: "2026-01-18",
    category: "Sales",
    description: "Weekend sales - Colombo",
    profit: 10,
    payment: "Mixed",
    branch: "Colombo",
  },
  {
    id: "P027",
    date: "2026-01-18",
    category: "Sales",
    description: "Weekend sales - Kandy",
    profit: 20,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P028",
    date: "2026-01-18",
    category: "Sales",
    description: "Weekend sales - Galle",
    profit: 10,
    payment: "Mixed",
    branch: "Galle",
  },
  {
    id: "P029",
    date: "2026-01-15",
    category: "Catering",
    description: "Company lunch - Colombo",
    profit: 20,
    payment: "Bank Transfer",
    branch: "Colombo",
  },
  {
    id: "P030",
    date: "2026-01-10",
    category: "Catering",
    description: "Family gathering - Galle",
    profit: 10,
    payment: "Card",
    branch: "Galle",
  },
  {
    id: "P031",
    date: "2026-01-05",
    category: "Sales",
    description: "New Year special sales",
    profit: 20,
    payment: "Mixed",
    branch: "Colombo",
  },
  {
    id: "P032",
    date: "2026-01-01",
    category: "Sales",
    description: "New Year Day sales",
    profit: 10,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P033",
    date: "2025-12-31",
    category: "Sales",
    description: "New Year's Eve event",
    profit: 20,
    payment: "Mixed",
    branch: "Colombo",
  },
  {
    id: "P034",
    date: "2025-12-31",
    category: "Sales",
    description: "New Year's Eve event",
    profit: 10,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P035",
    date: "2025-12-31",
    category: "Sales",
    description: "New Year's Eve event",
    profit: 20,
    payment: "Mixed",
    branch: "Galle",
  },
  {
    id: "P036",
    date: "2025-12-25",
    category: "Sales",
    description: "Christmas Day special",
    profit: 10,
    payment: "Mixed",
    branch: "Colombo",
  },
  {
    id: "P037",
    date: "2025-12-25",
    category: "Sales",
    description: "Christmas Day special",
    profit: 20,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P038",
    date: "2025-12-24",
    category: "Catering",
    description: "Christmas party - Colombo",
    profit: 10,
    payment: "Bank Transfer",
    branch: "Colombo",
  },
  {
    id: "P039",
    date: "2025-12-20",
    category: "Catering",
    description: "Christmas party - Kandy",
    profit: 20,
    payment: "Card",
    branch: "Kandy",
  },
  {
    id: "P040",
    date: "2025-12-15",
    category: "Sales",
    description: "Mid-month sales",
    profit: 10,
    payment: "Mixed",
    branch: "Galle",
  },
  {
    id: "P041",
    date: "2025-12-10",
    category: "Catering",
    description: "Office party - Colombo",
    profit: 20,
    payment: "Bank Transfer",
    branch: "Colombo",
  },
  {
    id: "P042",
    date: "2025-12-05",
    category: "Sales",
    description: "Weekend sales",
    profit: 10,
    payment: "Mixed",
    branch: "Kandy",
  },
  {
    id: "P043",
    date: "2025-12-01",
    category: "Sales",
    description: "December opening sales",
    profit: 20,
    payment: "Mixed",
    branch: "Colombo",
  },
];